### ISSUE TITLE
هل هناك وقت تقريبي لمتى تنتهي 200 حلقة؟

### ISSUE THREAD

**Issue by EL-MEHDI-ESSAADI** [ElzeroWebSchool/JavaScript_Bootcamp#4]

**Comment by UBA-code** [comment]
شهر او شهرين بالكثير

**Comment by ElzeroWebSchool** [comment]
الاسابيع الباقية شغال عليها حاليا وسايب كل حاجة علشان انتهي منها ممكن تقول اسبوعين ونخلص تماما باذن الله الابلود

**Comment by EL-MEHDI-ESSAADI** [comment]
الحمد الله أخي أسامة أكملت الأسابيع المتبقية من الكورس المدكورة في الريدمي  من خلال كورس الجافاسكريبت القديم و مصادر أخرى و طبقت أيضا, الأن تعلمت أساسيات الرياكت و بطبق عليها .
ديما البداية هي الصعبة و أنت كنت السبب في تسهيلها ,  الله يجزاك خير 🖤 

![Screenshot (5)](https://user-images.githubusercontent.com/79756353/166085646-be33d00a-0ada-448e-af48-ce3ce3b61c32.png)

**Comment by ElzeroWebSchool** [comment]
> الحمد الله أخي أسامة أكملت الأسابيع المتبقية من الكورس المدكورة في الريدمي من خلال كورس الجافاسكريبت القديم و مصادر أخرى و طبقت أيضا, الأن تعلمت أساسيات الرياكت و بطبق عليها . ديما البداية هي الصعبة و أنت كنت السبب في تسهيلها , الله يجزاك خير 🖤
> 
> ![Screenshot (5)](https://user-images.githubusercontent.com/79756353/166085646-be33d00a-0ada-448e-af48-ce3ce3b61c32.png)

تسلم ايدك جدا يا بطل

**Comment by ElzeroWebSchool** [comment]
إنتهى الكورس والحمد لله
